
#FROM vcalvi/rpi4-tf-ssh:v1.0
FROM vcalvi/rpi4-tf-opencv-ssh:v1.0

RUN wget http://192.168.1.50:9000/KHADAS-PI-AI-STICK/Orange%20PI%20AI%20Stick/arm7l/GTISDK-Linux_armv7l_v4.5.1.0_190823.tgz
RUN tar zxvf GTISDK-Linux_armv7l_v4.5.1.0_190823.tgz 
RUN rm GTISDK-Linux_armv7l_v4.5.1.0_190823.tgz

RUN apt-get install usbutils udev -y
RUN apt install \
	libx11-dev \
	libgtk2.0-dev \
	pkg-config \
	libavcodec-dev \
	libavformat-dev \
	libswscale-dev \
	libjpeg-dev \
	python-numpy \
	python-tk -y

RUN python -m pip install setuptools
#RUN python -m pip install --user Python/Lib/gtiClassify/





